version: '3.8'

services:
  wordpress:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER_FILE: /run/secrets/wordpress_db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
      WORDPRESS_DB_NAME_FILE: /run/secrets/wordpress_db_name
      WORDPRESS_REDIS_HOST: redis
    secrets:
      - wordpress_db_user
      - wordpress_db_password
      - wordpress_db_name
    volumes:
      - "./wordpress_data/:/var/www/html"
      - "./wp-content/plugins/CustomWooCommerceRedis/:/var/www/html/wp-content/plugins/custom-woocommerce-redis-integration"
      - "./vendor/:/var/www/html/wp-content/plugins/custom-woocommerce-redis-integration/vendor"

  phpunit:
    image: wordpress:latest
    depends_on:
      - wordpress
    volumes:
      - "./wordpress_data/:/var/www/html" 
      - ./wp-content/plugins/CustomWooCommerceRedis:/var/www/html/wp-content/plugins/custom-woocommerce-redis-integration
      - "./vendor/:/var/www/html/wp-content/plugins/custom-woocommerce-redis-integration/vendor"
    entrypoint: /bin/bash
    command: -c "cd /var/www/html/wp-content/plugins/custom-woocommerce-redis-integration && vendor/bin/phpunit --configuration phpunit.xml"
    
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/wordpress_db_name
      MYSQL_USER_FILE: /run/secrets/wordpress_db_user
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - wordpress_db_user
      - wordpress_db_password
      - wordpress_db_name
      - mysql_root_password
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6380:6379" # Map container port 6379 to host port 6380
    volumes:
      - redis_data:/data

secrets:
  wordpress_db_user:
    file: ./wordpress_db_user.txt
  wordpress_db_password:
    file: ./wordpress_db_password.txt
  wordpress_db_name:
    file: ./wordpress_db_name.txt
  mysql_root_password:
    file: ./mysql_root_password.txt

volumes:
  db_data:
  redis_data: 
  wordpress_data:
