name: Release WooCommerce Redis Plugin

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write  # Only if you need to manage issues
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zip
        run: sudo apt-get install zip

      - name: Create zip file
        run: |
          zip -r CustomWooCommerceRedis.zip wp-content/plugins/CustomWooCommerceRedis \
          -x "*tests*" \
          -x "*phpunit.xml*" \
          -x "*test-results*" \
          -x "*.phpunit.result.cache" \
          -x "*.phpunit.cache"

      - name: Extract tag name
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ steps.extract_tag.outputs.tag }}
            release_name: Release ${{ steps.extract_tag.outputs.tag }}
            draft: false
            prerelease: false
