name: Create Archive
on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Zorg ervoor dat alle tags en branches worden opgehaald

      - name: Install zip
        run: sudo apt-get install zip

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'WooRedisCache.zip'
          directory: 'wp-content/plugins/CustomWooCommerceRedis'
          path: '.'
          exclusions: 'tests/* phpunit.xml test-results/* *.phpunit.result.cache *.phpunit.cache'

      - name: Upload Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "WooRedisCache.zip"
          tag: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
