name: Release WooCommerce Redis Plugin

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write  # Only if je issues nodig hebt
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Zorg ervoor dat alle tags en branches worden opgehaald

      - name: Install zip
        run: sudo apt-get install zip

      - name: Create directory for zip
        run: mkdir -p release_files

      - name: Copy plugin files
        run: cp -r wp-content/plugins/CustomWooCommerceRedis/* release_files/

      - name: Remove unwanted files
        run: |
          rm -rf release_files/tests
          rm -f release_files/phpunit.xml
          rm -f release_files/test-results/*
          rm -f release_files/*.phpunit.result.cache
          rm -f release_files/*.phpunit.cache

      - name: Verify release files directory
        run: |
          echo "Release files directory: $(pwd)/release_files"
          ls -la release_files

      - name: Create zip file
        run: |
          cd release_files
          zip -r ../WooRedisCache.zip .
      
      - name: Verify zip contents
        run: unzip -l WooRedisCache.zip

      - name: Determine and create new tag
        id: new_tag
        run: |
          # Controleer of er tags bestaan
          if git fetch --tags && git tag | grep -q .; then
            LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "Laatste tag: $LAST_TAG"
            NEW_TAG="v$(echo $LAST_TAG | sed 's/v//' | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"
          else
            echo "Geen bestaande tags gevonden. Creëer initiële tag."
            NEW_TAG="v0.1.0"
          fi
          
          echo "Nieuwe tag: $NEW_TAG"
          
          # Creëer de nieuwe tag
          git tag $NEW_TAG
          git push origin $NEW_TAG
          
          # Zet de nieuwe tag als output
          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.new_tag.outputs.tag }}
          release_name: Release ${{ steps.new_tag.outputs.tag }}
          draft: false
          prerelease: false
          assets: WooRedisCache.zip
