name: Release WooCommerce Redis Plugin

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write  # Only if you need to manage issues
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Zorg ervoor dat alle tags worden opgehaald

      - name: Install zip
        run: sudo apt-get install zip

      - name: Create zip file
        run: |
          zip -r CustomWooCommerceRedis.zip wp-content/plugins/CustomWooCommerceRedis \
          -x "*tests*" \
          -x "*phpunit.xml*" \
          -x "*test-results*" \
          -x "*.phpunit.result.cache" \
          -x "*.phpunit.cache"

      - name: Bepaal en creëer nieuwe tag
        id: new_tag
        run: |
          # Haal de laatste tag op en verhoog het versienummer
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Laatste tag: $LAST_TAG"
          NEW_TAG="v$(echo $LAST_TAG | sed 's/v//' | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"
          echo "Nieuwe tag: $NEW_TAG"
          
          # Creëer de nieuwe tag
          git tag $NEW_TAG
          git push origin $NEW_TAG
          
          # Zet de nieuwe tag als output
          echo "::set-output name=tag::$NEW_TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ steps.new_tag.outputs.tag }}
            release_name: Release ${{ steps.new_tag.outputs.tag }}
            draft: false
            prerelease: false
