name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Check PHP version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      working-directory: ${{ github.workspace }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    # Fail the workflow if cache not found
    - name: Check if Composer cache is found
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: echo "::error::Composer cache not found"
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      working-directory: ${{ github.workspace }}

    # Run PHPUnit tests
    - name: Run PHPUnit tests
      run: composer test
      working-directory: ${{ github.workspace }}
